---
- name: Install Arch packages
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Arch packages on fresh OS
      community.general.pacman:
        name: base-devel,git,github-cli,code,chezmoi,alacritty,starship,neovim,micro,qtile,rofi,feh,picom,conky,ansible,dagger,docker,kubectl,k9s,helm,kustomize,terraform,openssh,firefox,age,obsidian,imagemagick,zsh,zsh-completions,zsh-autosuggestions,zsh-syntax-highlighting,lxsession,lxappearance,flux-bin,ripgrep,thunar,ranger,yamllint,fzf,dunst,tree,bat,man-pages,man-db,nodejs,npm,playerctl,pacman-contrib,lightdm-webkit-theme-aether,lightdm-slick-greeter,kubectx,kustomize,cronie,betterlockscreen,autorandr,python-jmespath,python-dbus-next,python-pip,shutter,unzip,xorg,wine,kitty,snapper,shutter,postgresql,dbeaver,pavucontrol,papirus-icon-theme,openvpn,npm,linux-lts,linux-lts-headers,jq,btop,fastfetch,dotnet-host,dotnet-runtime,dotnet-runtime-7.0-bin,dotnet-sdk,dotnet-sdk-7.0-bin,dotnet-targeting-pack-7.0-bin,argocd,atuin,noto-fonts-cjk,noto-fonts-emoji,nodejs


    - name: Install Homebrew
      community.general.homebrew:
        state: present

    - name: Add Linuxbrew configuration to .zshrc
      ansible.builtin.blockinfile:
        path: "/home/tnea/.zshrc"
        block: |
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >> "/home/tnea/.zshrc"


    - name: Clone Chezmoi repo
      ansible.builtin.git:
        repo: https://github.com/tmayweather/dotfiles.git
        dest: /home/tnea/dotfiles
        single_branch: true
        version: main
      environment:
        GIT_SSH_COMMAND: "ssh -o ForwardAgent=yes"
